pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
            	dir('springbootken') {
            		sh 'sudo ./mvnw clean spring-boot:run'
            	}
            }
        }
    }
}